import 'dart:async';

import 'package:floor/floor.dart';
import 'package:flutter/foundation.dart';
import 'package:sqflite/sqflite.dart' as sqflite;

import 'date_time_converter.dart';
import 'note.dart';
import 'note_dao.dart';

part 'database.g.dart';

/// SQLite database of the application.
///
/// The implementation is generated by Floor (`database.g.dart`) and exposes
/// the [NoteDao] that is used by the screens. The database file is opened
/// once with [open] and shared through [instance], so the rest of the app
/// never has to deal with opening or closing it.
@Database(entities: [Note], version: 2)
@TypeConverters([DateTimeConverter])
abstract class AppDatabase extends FloorDatabase {
  AppDatabase();

  /// Data access object for the `notes` table.
  NoteDao get noteDao;

  static AppDatabase? _instance;

  /// Changes that upgrade a database file created by an older version of the
  /// app, so existing notes survive an app update.
  static final List<Migration> _migrations = [
    // Version 2 added the readable location name of a note.
    Migration(1, 2, (database) async {
      await database.execute('ALTER TABLE notes ADD COLUMN locationName TEXT');
    }),
  ];

  /// Whether [open] has already created the shared instance.
  static bool get isOpen => _instance != null;

  /// The shared database instance.
  ///
  /// Throws a [StateError] when the database has not been opened yet, so it
  /// should only be used after [open] completed successfully.
  static AppDatabase get instance {
    final database = _instance;
    if (database == null) {
      throw StateError(
        'AppDatabase.open() has to be awaited before the database is used.',
      );
    }
    return database;
  }

  /// Opens the database stored as [fileName] in the platform database folder.
  ///
  /// Calling the method more than once returns the instance created by the
  /// first call, so the app always works with the same database and it is
  /// never opened twice.
  static Future<AppDatabase> open({String fileName = 'noteapp.db'}) async {
    final existing = _instance;
    if (existing != null) {
      return existing;
    }
    final database = await $FloorAppDatabase.databaseBuilder(fileName)
        .addMigrations(_migrations)
        .build();
    _instance = database;
    return database;
  }

  /// Opens an in memory database and makes it the shared instance.
  ///
  /// Only used by tests, where the notes must not survive the test case.
  @visibleForTesting
  static Future<AppDatabase> openInMemory() async {
    final database =
        await $FloorAppDatabase.inMemoryDatabaseBuilder().build();
    _instance = database;
    return database;
  }

  /// Closes the database and clears the shared instance.
  static Future<void> closeInstance() async {
    final database = _instance;
    _instance = null;
    await database?.close();
  }
}
